securite:
    resource: "@SecuriteBundle/Controller/"
    type:     annotation
    prefix:   /

core:
    resource: "@CoreBundle/Controller/"
    type:     annotation
    prefix:   /

user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix: /user

backend:
    resource: "@BackendBundle/Controller/"
    type:     annotation
    prefix:   /backend

mentorat:
    resource: "@MentoratBundle/Controller/"
    type:     annotation
    prefix:   /dashboard

admin:
    resource: "@AdminBundle/Controller/"
    type:     annotation
    prefix:   /admin3744

notification:
    resource: "@NotificationBundle/Controller/"
    type:     annotation
    prefix:   /notifications

# FOS Routes
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_user_group:
    resource: "@FOSUserBundle/Resources/config/routing/group.xml"
    prefix: /group
