# Core Routes
app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    prefix:   /

mentor:
    resource: "@MentorBundle/Controller/"
    type:     annotation

user:
    resource: "@UserBundle/Controller/"
    type:     annotation

admin:
    resource: "@AdminBundle/Controller/"
    type:     annotation

# FOS Routes
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"