core:
    resource: "@CoreBundle/Controller/"
    type:     annotation
    prefix:    /

api:
    resource: "@ApiBundle/Controller/"
    type:     annotation
    prefix:    /api

securite:
    resource: "@SecuriteBundle/Controller/"
    type:     annotation
    prefix:   /security

user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /user

backend:
    resource: "@BackendBundle/Controller/"
    type:     annotation
    prefix:   /backend

mentorat:
    resource: "@MentoratBundle/Controller/"
    type:     annotation
    prefix:   /dashboard

admin:
    resource: "@AdminBundle/Controller/"
    type:     annotation
    prefix:   /admin3744

notification:
    resource: "@NotificationBundle/Controller/"
    type:     annotation
    prefix:   /notifications

facturation:
    resource: "@FacturationBundle/Controller/"
    type:     annotation
    prefix:   /facturation

# FOS Routes
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

fos_user_group:
    resource: "@FOSUserBundle/Resources/config/routing/group.xml"
    prefix: /group
