notification:
    resource: "@NotificationBundle/Controller/"
    type:     annotation
    prefix:   /

core:
    resource: "@CoreBundle/Controller/"
    type:     annotation
    prefix:   /

backend:
    resource: "@BackendBundle/Controller/"
    type:     annotation
    prefix:   /backend

mentorat:
    resource: "@MentoratBundle/Controller/"
    type:     annotation
    prefix:   /dashboard

user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /

admin:
    resource: "@AdminBundle/Controller/"
    type:     annotation
    prefix:   /admin3744

# FOS Routes
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"