# app/config/security.yml
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha1

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
            form_login:
                login_path: fos_user_security_login
                check_path: fos_user_security_check
            logout:
                path:    fos_user_security_logout
                target: /
            remember_me:
                secret:    %secret%
            logout:       true
            anonymous:    true

    access_control:
        - { path: ^/login$,     role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register,   role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting,  role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin3744/, role: ROLE_ADMIN }
        #- { path: ^/backend,    role: [ROLE_ADMIN, ROLE_SUPERVISEUR_MENTOR] }
        - { path: ^/dashboard,  roles: [ROLE_ADMIN, ROLE_SUPERVISEUR_MENTOR, ROLE_MENTOR] }
