# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    core.admin:
        class: AdminBundle\Services\Admin
        arguments: ["@doctrine.orm.entity_manager", "@form.factory", "@session", "@security.token_storage"]

    core.user_admin:
        class: AdminBundle\Services\UserAdmin
        arguments: ["@doctrine.orm.entity_manager"]

    core.statistiques:
        class: AdminBundle\Services\Statistiques
        arguments: ["@doctrine.orm.entity_manager"]

    core.back:
        class: BackendBundle\Services\Back
        arguments: ["@doctrine.orm.entity_manager", "@form.factory", "@session","@security.token_storage"]

    core.archive:
        class: AdminBundle\Services\Archive
        arguments: ["@doctrine.orm.entity_manager", "@session"]

    core.mentore:
        class: MentoratBundle\Services\MentoreService
        arguments: ["@doctrine.orm.entity_manager", "@form.factory", "@session", "@security.token_storage"]

    core.user:
        class: UserBundle\Services\UserService
        arguments: ["@doctrine.orm.entity_manager", "@form.factory", "@session", "@security.token_storage"]


    # Used to registrer the users with FOS !
    core.user_register:
        class: UserBundle\Form\RegistrationType
        tags:
        - { name: form.type, alias: app_user_registration }
