# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    core.admin:
        class: AdminBundle\Services\Admin

    core.back:
        class: BackendBundle\Services\Back
        arguments: ["@doctrine.orm.entity_manager", "@form.factory", "@session"]

    # Used to registrer the users with FOS !
    core.user_register:
        class: UserBundle\Form\RegistrationType
        tags:
        - { name: form.type, alias: app_user_registration }
