<?php

namespace UserBundle\Repository;

/**
 * CompetencesRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompetencesRepository extends \Doctrine\ORM\EntityRepository
{
    public function getCompetencesByMentor($id)
    {
        return $this->createQueryBuilder('c')
                    ->innerJoin('c.user', 'u')
                        ->addSelect('u')
                    ->where('u.id = :id')
                        ->setParameter('id', $id)
                    ->getQuery()
                    ->getResult();
    }
}
