<?php

namespace UserBundle\Repository;

/**
 * InformationsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InformationsRepository extends \Doctrine\ORM\EntityRepository
{
}
