<?php

namespace UserBundle\Repository;

/**
 * MentoreRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MentoreRepository extends \Doctrine\ORM\EntityRepository
{
}
