<?php

namespace UserBundle\Repository;

/**
 * UserRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function getMentors()
    {
        return $this->createQueryBuilder('m')
                    ->where('m.roles = :role')
                        ->setParameter('role', $role = 'ROLE_MENTOR')
                    ->getQuery()
                    ->getResult();
    }
}
