<?php

namespace BackendBundle\Repository;

/**
 * CompetencesRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompetencesRepository extends \Doctrine\ORM\EntityRepository
{
    public function getCompetencesByProject($id)
    {
        return $this->createQueryBuilder('c')
                    ->where('c.projet = :projet')
                        ->setParameter('projet', $id)
                    ->getQuery()
                    ->getResult();
    }
}
