<?php

namespace BackendBundle\Repository;

/**
 * CoursRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CoursRepository extends \Doctrine\ORM\EntityRepository
{
    public function getCoursByParcours($parcours)
    {
        return $this->createQueryBuilder('c')
                    ->where('c.parcours = :parcours')
                        ->setParameter('parcours', $parcours)
                    ->getQuery()
                    ->getResult();
    }
}
