<?php

namespace BackendBundle\Repository;

/**
 * InformationMentoratRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InformationMentoratRepository extends \Doctrine\ORM\EntityRepository
{
}
