<?php

namespace BackendBundle\Repository;

/**
 * ParcoursRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParcoursRepository extends \Doctrine\ORM\EntityRepository
{

    public function getParcours()
    {
        return $this->createQueryBuilder('p')
                    ->where('p.archived = false')
                    ->getQuery()
                    ->getResult();
    }

    public function getParcoursArchived()
    {
        return $this->createQueryBuilder('p')
            ->where('p.archived = true')
            ->getQuery()
            ->getResult();
    }

    public function getParcoursPlus()
    {
        return $this->createQueryBuilder('pp')
                    ->innerJoin('pp.abonnement', 'a')
                        ->addSelect('a')
                    ->where('a.libelle = :abonnement')
                        ->setParameter('abonnement', $abonnement = 'Premium Plus')
                    ->getQuery()
                    ->getResult();
    }

    public function getParcoursClass()
    {
        return $this->createQueryBuilder('pp')
                    ->innerJoin('pp.abonnement', 'a')
                        ->addSelect('a')
                    ->where('a.libelle = :abonnement')
                        ->setParameter('abonnement', $abonnement = 'Premium Class')
                    ->getQuery()
                    ->getResult();
    }
}
