<?php

namespace BackendBundle\Repository;

/**
 * ParcoursRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParcoursRepository extends \Doctrine\ORM\EntityRepository
{
    public function getParcoursPlus()
    {
        return $this->createQueryBuilder('pp')
                    ->where('pp.abonnement = :abonnement')
                        ->setParameter('abonnement', $abonnement = 'Premium Plus')
                    ->getQuery()
                    ->getResult();
    }

    public function getParcoursClass()
    {
        return $this->createQueryBuilder('pp')
            ->where('pp.abonnement = :abonnement')
            ->setParameter('abonnement', $abonnement = 'Premium Class')
            ->getQuery()
            ->getResult();
    }
}
