<?php

namespace BackendBundle\Repository;

/**
 * ProjetRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjetRepository extends \Doctrine\ORM\EntityRepository
{
    public function getProjetByParcours($parcours)
    {
        return $this->createQueryBuilder('p')
                    ->where('p.parcours = :parcours')
                        ->setParameter('parcours', $parcours)
                    ->getQuery()
                    ->getResult();
    }

    public function getProjetTermine()
    {
        return $this->createQueryBuilder('p')
                    ->where('p.status = Validé')
                    ->getQuery()
                    ->getResult();
    }
}
