<?php

namespace BackendBundle\Repository;

/**
 * StateRelationshipRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StateRelationshipRepository extends \Doctrine\ORM\EntityRepository
{
}
