<?php

namespace MentoratBundle\Repository;

/**
 * FormationEtapeUserRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FormationEtapeUserRepository extends \Doctrine\ORM\EntityRepository
{
}
