<?php

namespace MentoratBundle\Repository;

/**
 * FormationEtapeRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FormationEtapeRepository extends \Doctrine\ORM\EntityRepository
{
}
