<?php

namespace MentoratBundle\Repository;

/**
 * MentoreRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MentoreRepository extends \Doctrine\ORM\EntityRepository
{
    public function getMentoresPlus()
    {
        return $this->createQueryBuilder('pp')
                    ->where('pp.parcours.abonnement = :abonnement')
                        ->setParameter('abonnement', $abonnement = 'Premium Plus')
                    ->getQuery()
                    ->getResult();
    }

    public function getMentoresClass()
    {
        return $this->createQueryBuilder('pp')
            ->where('pp.parcours.abonnement = :abonnement')
            ->setParameter('abonnement', $abonnement = 'Premium Class')
            ->getQuery()
            ->getResult();
    }

    public function getNewMentores($days)
    {
        return $this->createQueryBuilder('m')
                    ->where('m.date_start <= :days')
                        ->setParameter('days', $days)
                    ->getQuery()
                    ->getResult();
    }
}
