<?php

namespace MentoratBundle\Repository;

/**
 * MentorMentoreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MentorMentoreRepository extends \Doctrine\ORM\EntityRepository
{
}
