<?php

namespace MentoratBundle\Repository;

/**
 * MentoreRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MentoreRepository extends \Doctrine\ORM\EntityRepository
{
    public function getNewMentores($days)
    {
        return $this->createQueryBuilder('m')
                    ->where('m.date_start <= :days')
                        ->setParameter('days', $days)
                    ->getQuery()
                    ->getResult();
    }

    public function getMentoresWaiting()
    {
        return $this->createQueryBuilder('s')
                    ->where('s.status = :status')
                        ->setParameter('status', $status = 'En attente')
                    ->getQuery()
                    ->getResult();
    }

    public function getStudentsByMentor($id)
    {
        return $this->createQueryBuilder('s')
                    ->innerJoin('s.suivi', 'ss')
                        ->addSelect('ss')
                    ->where('ss.mentor = :id')
                        ->setParameter('id', $id)
                    ->getQuery()
                    ->getResult();
    }
}
