<?php

namespace MentoratBundle\Repository;

/**
 * RecrutementVoteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecrutementVoteRepository extends \Doctrine\ORM\EntityRepository
{
}
