<?php

namespace MentoratBundle\Repository;

/**
 * RecrutementQuestionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecrutementQuestionRepository extends \Doctrine\ORM\EntityRepository
{
}
