<?php

namespace MentoratBundle\Repository;

/**
 * RecrutementReponseRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecrutementReponseRepository extends \Doctrine\ORM\EntityRepository
{
}
