<?php

namespace MentoratBundle\Repository;

/**
 * SessionsRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SessionsRepository extends \Doctrine\ORM\EntityRepository
{
    public function getSessionsbyMentore($id)
    {
        return $this->createQueryBuilder('s')
                    ->where('s.mentore = :id')
                        ->setParameter('id', $id)
                    ->orderBy('s.dateSession', 'DESC')
                    ->getQuery()
                    ->getResult();
    }
}
