<?php

namespace MentoratBundle\Repository;

/**
 * SuiviRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SuiviRepository extends \Doctrine\ORM\EntityRepository
{
    public function getSuiviByStudent($id)
    {
        return $this->createQueryBuilder('s')
                    ->innerJoin('s.notes', 'n')
                        ->addSelect('n')
                    ->leftJoin('s.mentore', 'm')
                        ->addSelect('m')
                    ->leftJoin('s.parcours', 'p')
                        ->addSelect('p')
                    ->where('m.id = :id')
                        ->setParameter('id', $id)
                    ->getQuery()
                    ->getResult();
    }

    /**
     * @param $mentor
     *
     * @return mixed
     */
    public function countMentoreByMentorDisplayed($mentor)
    {
        return $this->createQueryBuilder('s')
                    ->select('COUNT(s)')
                    ->where('s.mentor = :mentor')
                        ->setParameter('mentor', $mentor)
                    ->getQuery()
                    ->getSingleScalarResult();
    }
}
