<?php

namespace MentoratBundle\Repository;

/**
 * TutorialCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TutorialCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
