<?php

namespace NotificationBundle\Repository;

/**
 * EventsRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventsRepository extends \Doctrine\ORM\EntityRepository
{
    public function getEventsByUser($id)
    {
        return $this->createQueryBuilder('e')
                    ->innerJoin('e.users', 'u')
                        ->addSelect('u')
                    ->where('u.id = :id')
                        ->setParameter('id', $id)
                    ->getQuery()
                    ->getResult();
    }
}
